### Get请求 测试无参数
GET {{url}}
#Accept: application/json

### Get请求
GET {{url}}/days
#Accept: application/json


### Get请求
GET {{url}}/api/user/index


### Get请求
GET {{url}}/test/post/beartbeat


### Get请求
GET {{url}}/api/get



### POST请求 Send POST request with json body
POST {{url}}/user2/add
Content-Type: application/json

{
  "username":"111",
  "password":"sa",
  "userInfo":{
    "age":19,
    "gender":"男"
  }
}
